### ISSUE TITLE
meta sync demands an s-variables-common~.json file

### ISSUE THREAD

**Issue by ChaosSmith** [serverless/serverless-meta-sync#19]
I have come across a curious issue when attempting to run sls meta sync. I place the bucket location/region in s-variables-common.json and then run the command only to be told 

`ServerlessError: Error reading file /home/zac/lootbag/serverless-starter/_meta/variables/s-variables-common~.json
      ENOENT: no such file or directory, open '/home/zac/lootbag/serverless-starter/_meta/variables/s-variables-common~.json'
    at new ServerlessError (/home/zac/.npm-global/lib/node_modules/serverless/lib/Error.js:17:11)
    at Object.module.exports.readFileSync (/home/zac/.npm-global/lib/node_modules/serverless/lib/utils/index.js:187:13)
    at /home/zac/.npm-global/lib/node_modules/serverless/lib/Serializer.js:328:40
From previous event:
    at Stage.deserializeStage (/home/zac/.npm-global/lib/node_modules/serverless/lib/Serializer.js:320:27)
    at Stage.deserialize (/home/zac/.npm-global/lib/node_modules/serverless/lib/Serializer.js:27:57)
    at Stage.load (/home/zac/.npm-global/lib/node_modules/serverless/lib/Stage.js:26:19)
    at /home/zac/.npm-global/lib/node_modules/serverless/lib/Serializer.js:127:32
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at /home/zac/.npm-global/lib/node_modules/serverless/lib/Serializer.js:103:14
From previous event:
    at Project.deserializeProject (/home/zac/.npm-global/lib/node_modules/serverless/lib/Serializer.js:92:10)
    at Project.deserialize (/home/zac/.npm-global/lib/node_modules/serverless/lib/Serializer.js:27:57)
    at Project.load (/home/zac/.npm-global/lib/node_modules/serverless/lib/Project.js:36:19)
    at /home/zac/.npm-global/lib/node_modules/serverless/lib/Serverless.js:87:35
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Serverless.init (/home/zac/.npm-global/lib/node_modules/serverless/lib/Serverless.js:79:10)
    at Object.<anonymous> (/home/zac/.npm-global/lib/node_modules/serverless/bin/serverless:17:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3`

Creating s-variables-common~.json allows the program to proceed as expected, even if its nothing more than an empty json file. On the odd occasion however the error will return and ask for the file with additional ~, record so far is ~~~~.

Was just wondering if anyone else had experienced this behaviour? I am using serverless-graphql which came packaged with version 1.0 meta-sync, and have reproduced it by removing and reinstalling the plugin, installing a fresh version of serverless-graphql, and with a serverless-starter install. I will try and reproduce it on a different computer soon.

**Comment by ChaosSmith** [comment]
Issue was ubuntu's text editor leaving behind temporary files, closing the issue.
